import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState();

  const url = 'https://planets-info-by-newbapi.p.rapidapi.com/api/v1/planet/list';

  useEffect(() => {
    const options = {
      method: 'GET',
      headers: {
        'X-RapidAPI-Key': '12d272bc5cmsh8217a7ecc290e1fp1ae971jsnbb83b59ab291',
        'X-RapidAPI-Host': 'planets-info-by-newbapi.p.rapidapi.com'
      }
    };

    fetch(url, options)
      .then(response => response.json())
      .then(response => {
        console.log(response);
        setData(response);
      })
      .catch(err => {
        console.error(err);
      })

  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          data && data.map((d) => {
            return(
              <div key={d.id}>
                <h2>{d.name}</h2>
                {d.description}
                <Image src={d.imgSrc[0].img} width="50" height="50" alt={d.name}/>
              </div>
            )
          })
        }
      </main>
    </>
  )
}
